Add support for imperial units
CelestiaProject/Celestia pull request #1121
Opened 2021-09-27 15:05 UTC by levinli303

Had quite a few reviews from Play asking for supporting imperial units. These units are added but I'm not sure if they are the common ones.

mi, ft for length (km, m)
mi/s, ft/s for speed (km/s, m/s)
slug/ft^3 for density (1000 kg/m^3)
lb for mass (kg)

@SevenSpheres

2021-09-27 16:29 UTC, SevenSpheres submitted a review, later dismissed
> Units of slugs are not in common use. Pounds are (mis)used instead.
> Units of yards/sec are never used. Feet/sec are used instead. [I see this was already changed though]

(I'm assuming imperial units are optional and not displayed by default, correct?)

2021-09-27 17:44 UTC, SevenSpheres commented
> Should i use lb/ft^3 for density instead?

I guess so.

2021-09-28 05:15 UTC, 375gnu requested changes

2021-09-28 05:15 UTC, 375gnu commented on src/celestia/celestiacore.cpp
> +        if (config->measurementSystem == "Imperial")
too fragile, could you make it case-insensitive?

2021-09-28 05:56 UTC, 375gnu approved these changes

2021-09-28 06:03 UTC, merged