Ensure reproducibility of "random" template generation
CelestiaProject/Celestia pull request #1160
Opened 2021-11-15 23:31 UTC by ajtribick

- Add an implementation of [Bob Jenkins' small fast noncryptographic random number generator](http://burtleburtle.net/bob/rand/talksmall.html), adapted to meet the [UniformRandomBitGenerator](https://en.cppreference.com/w/cpp/named_req/UniformRandomBitGenerator) named requirement to allow it to be used with the distributions in the `<random>` header.
- Use separate generators in galaxy, globular and Perlin noise generation to ensure these generations are independent.

The seed values are taken from the output of a random device. According to [this article by the creator of the PCG pseudorandom number generator](https://www.pcg-random.org/posts/bob-jenkins-small-prng-passes-practrand.html), this generator passes PractRand, and it's a lot smaller than the Mersenne Twister (which does not).

This ensures that the galaxy and globular cluster sprite distributions, and the shape of cms meshes is consistent between runs and across distributions.

2021-11-16 09:36 UTC, 375gnu requested changes

2021-11-16 09:36 UTC, 375gnu commented on src/celengine/galaxy.cpp
> +    celmath::Jsf32 rng(UINT32_C(0xa0030c29));
magic constants, we all like them! :)))

could you provide names for them with some descriptive comments?

2021-11-16 09:36 UTC, 375gnu commented on src/celmath/randutils.cpp
> +    a(UINT32_C(0xf1ea5eed)), b(seed), c(seed), d(seed)
please make one variable per line

2021-11-16 09:36 UTC, 375gnu commented on src/celmath/randutils.cpp
> +        (void)this->operator()();
I think it's better to add a private function and call it here and in operator, cause this like looks cryptic

2021-11-16 09:36 UTC, 375gnu commented on src/celmath/randutils.h
> +    static constexpr result_type max() { return UINT32_MAX; }
std::numeric_limits<result_type>::max()

2021-11-16 09:36 UTC, 375gnu commented on src/celmath/randutils.h
> +    static constexpr result_type max() { return UINT32_MAX; }
std::numeric_limits<result_type>::min()

2021-11-17 11:29 UTC, ajtribick commented
Withdrawing this as it's incomplete: while it guarantees the underlying RNG is consistent between platforms and runs, the implementations of the distributions (`std::uniform_int_distribution` and `std::uniform_real_distribution`) can and do vary between implementations, so this only gets us partially there.

2021-11-17 11:29 UTC, closed without merging