Reverse last point's scale value
CelestiaProject/Celestia pull request #1417
Opened 2022-09-09 11:55 UTC by levinli303

2022-09-09 15:20 UTC, 375gnu approved these changes

2022-09-10 13:19 UTC, 375gnu requested changes

2022-09-10 13:19 UTC, 375gnu commented on src/celengine/curveplot.cpp
> +            data[index - 1].scale = -data[index - 1].scale;
it seams `data[index]` and `data[index + 1]` should be used in the left part

2022-09-10 13:22 UTC, 375gnu submitted a review, later dismissed

2022-09-10 13:35 UTC, 375gnu commented
hmm, i don't see differences. orbits still have gaps.

2022-09-14 11:37 UTC, levinli303 commented
the position for points of triangulated lines is line point position offset by the line width in a certain direction. this direction is calculated by the line segment direction rotated 90 degree. all the points before the last points have the line direction of prev->next. however to compensate the missing next point for last point, we used the point second to last as last point's next point, which causes the direction to be the opposite, this PR fixes this.

I recorded a video before the fix in gpu debugger. the blue point in the geometry window is the selected point in the table below. you can see that before the last two points, for every pair of points, the point above the line center comes first. (on the right side you can see the #1414 issue, but it is not relevant to this PR)

https://user-images.githubusercontent.com/17924287/190142789-191f915f-7d11-41ad-b2cf-10cb388086cd.mov

2022-09-14 11:56 UTC, 375gnu approved these changes

2022-09-14 12:30 UTC, merged