Add EclipticXYZ to the stc file
CelestiaProject/Celestia pull request #1523
Opened 2023-01-26 18:44 UTC by ajtribick

This property allows specifying a star's position in rectangular coordinates in the ecliptic reference frame, matching the coordinates used in stars.dat. This enables a 1:1 conversion of stars.dat entries into the .stc file format.

Open to suggestions for a different name for this property.

2023-01-26 19:50 UTC, 375gnu approved these changes

2023-01-26 19:51 UTC, 375gnu commented
Regarding the property name maybe the forum is better place to discuss.

2023-01-27 18:26 UTC, ajtribick commented
Was looking at adding this to .dsc files when I noticed that it's already there. In the .dsc file it is called "Position", so might as well use that.

2023-01-28 11:49 UTC, 375gnu requested changes

2023-01-28 11:49 UTC, 375gnu commented on src/celengine/stardb.cpp
> +        // EclipticXYZ allows the position of the star to be specified in
EclipticXYZ left in comments

2023-01-28 13:34 UTC, ajtribick commented on src/celengine/stardb.cpp
> +        // EclipticXYZ allows the position of the star to be specified in
Fixed

2023-01-30 14:56 UTC, 375gnu approved these changes

2023-01-30 17:55 UTC, merged