Update lodspheremesh trigonometry calculations
CelestiaProject/Celestia pull request #1641
Opened 2023-03-14 19:32 UTC by ajtribick

- Ensure multiples of 90 degrees use exact values
- Refactor code

2023-03-15 09:43 UTC, 375gnu requested changes

2023-03-15 09:43 UTC, 375gnu commented on src/celengine/lodspheremesh.h
> +    std::unique_ptr<VertexArray> vertices{ nullptr };
std::vector ?

2023-03-15 09:43 UTC, 375gnu commented on src/celengine/lodspheremesh.h
> +    std::unique_ptr<IndexArray> indices{ nullptr };
std::vector?

2023-03-16 11:57 UTC, 375gnu approved these changes

2023-03-16 20:10 UTC, ajtribick commented
To replicate behaviour of the 4 textures `render()` API, we need to remove the `nullptr` elements from the `Texture*` array in a couple of places, so added the `erase` APIs to `ArrayVector`.

2023-03-17 09:03 UTC, 375gnu approved these changes

2023-03-17 18:46 UTC, merged