Add tool to reduce star database files to HIP entries only
CelestiaProject/Celestia pull request #1691
Opened 2023-04-22 12:42 UTC by ajtribick

As discussed in #1690

2023-04-22 13:15 UTC, 375gnu requested changes

2023-04-22 13:15 UTC, 375gnu commented on src/tools/stardb/prunestars.py
> +    if header != b'CELSTARS' or version != 0x0100:
what about version 0x0200?

2023-04-25 21:55 UTC, ajtribick commented on src/tools/stardb/prunestars.py
> +    if header != b'CELSTARS' or version != 0x0100:
So far, only version 0x0100 is permitted in stardb.cpp: https://github.com/CelestiaProject/Celestia/blob/15e15532e3acaf055525d74bdee73c07b79b4f10/src/celengine/stardb.cpp#L673

2023-04-26 06:30 UTC, 375gnu approved these changes

2023-04-26 10:26 UTC, merged