[qt] Add Celestia Guide to Help Menu
CelestiaProject/Celestia pull request #1824
Opened 2023-08-02 14:36 UTC by dave-kaye

This takes a compile time either/or choice for Wiki or Guide in Help menu and instead displays both.

2023-08-02 14:37 UTC, dave-kaye commented
The present code has an either/or choice for the Help menu, displaying the Wiki link or Guide manual link and calling it Manual in the menu. The compile directive if/else is permanently set to select the Wiki link.  This code adds a Qt action and Help menu item so both links are available to the user.

The guide manual is installed in the help subdirectory within the main Celestia data directory. If the --dir command line option is set, then the main Celestia data directory is the user's --dir directory option. After the existing initialization code locates the data directory, this code sets a variable to store the absolute path of the data directory; which remains constant in case some future code or Celx file should change the current directory setting. The guide manual path is derived from this variable. After the data directory is made the current directory by existing code, the QDir function currentPath() is used to guarantee an absolute path, since the variables setting the path could potentially be relative paths.

A CMake file entry for the help directory location will not work due to the command line option to change the data directory location.

This code has been tested with both the original location and --dir data directory option (both absolute and relative paths). It was developed on a Linux system, but the use of Qt QDir structures will make it portable to Windows and macOS. The guide manual is expected to be within the data directory structure, just as fonts, shaders and other items are. If a manual is not found, the existing code is automatically spawning an internet browser (user's default browser) and the browser will display a "file not found" message along with the expected path. There will be no system crash.

note:  The native Windows version of Celestia displays only the Guide in the Help menu, plus controls.txt. The GTK version displays neither but displays controls.txt.

2023-08-02 16:33 UTC, ajtribick commented
ui_preferences.h is a generated file, so not surprising it can't find it. The way we've currently got SonarScanner set up will always result in failures on external pull requests, since these cannot access the relevant tokens for uploading the analysis. I think this can be fixed but this will require adjusting the workflows.

2023-08-03 08:31 UTC, 375gnu requested changes

2023-08-03 08:31 UTC, 375gnu commented on src/celestia/qt/qtappwin.h
> +    QString m_celestia_data_dir;
```suggestion
    QString m_dataHome;
```

2023-08-03 08:31 UTC, 375gnu commented on src/celestia/qt/qtappwin.cpp
> +        m_celestia_data_dir = QDir::currentPath();
```suggestion
        m_dataHome = CONFIG_DATA_DIR;
        QDir::setCurrent(m_dataHome);
```

2023-08-03 08:31 UTC, 375gnu commented on src/celestia/qt/qtappwin.cpp
> +        m_celestia_data_dir = QDir::currentPath();
```suggestion
        m_dataHome = celestia_data_dir;
        QDir::setCurrent(m_dataHome);
```

2023-08-03 08:31 UTC, 375gnu commented on src/celestia/qt/qtappwin.cpp
> +    QDesktopServices::openUrl(QUrl::fromLocalFile(QDir::toNativeSeparators(m_celestia_data_dir) + QDir::toNativeSeparators("/help/CelestiaGuide.html")));
```suggestion
    QDesktopServices::openUrl(QUrl::fromLocalFile(QDir::toNativeSeparators(m_dataHome + "/help/CelestiaGuide.html")));
```

2023-08-04 15:21 UTC, closed without merging