Replace namespace celmath with celestia::math
CelestiaProject/Celestia pull request #1978
Opened 2023-11-13 08:05 UTC by 375gnu

2023-11-13 19:32 UTC, ajtribick requested changes

2023-11-13 19:32 UTC, ajtribick commented on src/celengine/deepskyobj.cpp
> +                                         math::Sphered(position, static_cast<double>(radius)),
Need to adjust indentation here

2023-11-13 19:32 UTC, ajtribick commented on src/celengine/dsorenderer.h
> +    celestia::math::Frustum    frustum         { celestia::math::degToRad(celestia::engine::standardFOV), 1.0f, 1.0f };
spacing should be fixed here

2023-11-13 19:32 UTC, ajtribick commented on src/celengine/galaxy.cpp
> +        math::transformRay(Eigen::ParametrizedLine<double, 3>(ray.origin() - getPosition(), ray.direction()),
Adjust indentation

2023-11-13 19:32 UTC, ajtribick commented on src/celengine/globular.cpp
> +                                     math::Sphered(getRadius() * (1.0f + kRadiusCorrection)),
indentation

2023-11-13 19:32 UTC, ajtribick commented on src/celestia/win32/winstarbrowser.cpp
> +            return (int) math::sign(star0->getApparentMagnitude(d0) -
Indentation needs adjusting

2023-11-13 21:35 UTC, 375gnu commented on src/celengine/deepskyobj.cpp
>                                           cosAngleToBoundCenter);
```suggestion
                                      math::Sphered(position, static_cast<double>(radius)),
                                      distanceToPicker,
                                      cosAngleToBoundCenter);
```

2023-11-13 21:35 UTC, 375gnu commented on src/celengine/dsorenderer.h
> +    celestia::math::Frustum    frustum         { celestia::math::degToRad(celestia::engine::standardFOV), 1.0f, 1.0f };
```suggestion
    celestia::math::Frustum frustum{ celestia::math::degToRad(celestia::engine::standardFOV), 1.0f, 1.0f };
```

2023-11-13 21:36 UTC, 375gnu commented on src/celengine/dsorenderer.h
>      DSODatabase*        dsoDB           { nullptr };
```suggestion
    celestia::math::Frustum frustum    { celestia::math::degToRad(celestia::engine::standardFOV), 1.0f, 1.0f };
    DSODatabase*        dsoDB           { nullptr };
```

2023-11-14 18:08 UTC, ajtribick approved these changes

2023-11-14 18:54 UTC, merged