Add support for zooming with a focus
CelestiaProject/Celestia pull request #2024
Opened 2023-12-23 01:55 UTC by levinli303

Add an option ENABLE_FOCUS_ZOOMING to support zooming (shift + left drag) with a focus by changing orientation during zooming so that the focus location (where the drag started) is kept where it was.

Also adding support for mobile pinch gesture based on this. Pinch on mobile is basically a focus and scale so it can be easily translated in to zooming with focus.

2023-12-24 09:23 UTC, 375gnu commented
Could you provide a test build for mobile users?

2023-12-24 09:31 UTC, levinli303 commented
> Could you provide a test build for mobile users?

I intend to provide beta testing via Google Play/App Store after this change is merged.

2023-12-24 09:51 UTC, 375gnu requested changes

2023-12-24 09:51 UTC, 375gnu commented on src/celestia/celestiacore.h
> +    struct MouseLocation
Actually, this type is not required, please use `Eigen::Vector2f` instead.

2023-12-24 09:51 UTC, 375gnu commented on src/celestia/celestiacore.cpp
> +    if ((renderer->getRenderFlags() & Renderer::ShowAutoMag))
```suggestion
    if ((renderer->getRenderFlags() & Renderer::ShowAutoMag) != 0)
```

2023-12-24 09:51 UTC, 375gnu commented on src/celestia/celestiacore.cpp
> +    Observer *observer = view->getObserver();
move this definition closer to its usage

2023-12-25 09:02 UTC, 375gnu approved these changes

2023-12-25 09:02 UTC, 375gnu commented on src/celestia/celestiacore.cpp
> +    Eigen::Vector2f focus { focusX, focusY };
please use `{}` only in class declarations.

2023-12-25 09:26 UTC, merged