Remove setlocale for fmt calls
CelestiaProject/Celestia pull request #2115
Opened 2024-02-18 10:46 UTC by levinli303

2024-02-18 14:42 UTC, ajtribick approved these changes

2024-02-18 21:00 UTC, 375gnu requested changes

2024-02-18 21:00 UTC, 375gnu commented on src/celestia/celestiacore.cpp
> +            auto loc = std::locale("");
please make this a CelestiaCore member so it's initialized only once

2024-02-19 09:47 UTC, 375gnu approved these changes

2024-02-19 09:49 UTC, 375gnu commented
i think we should rework how we handle locales, because we need LC_NUMERIC=C only for reading text catalogs and to work with URLs.

2024-02-19 11:15 UTC, merged

2024-02-20 01:46 UTC, levinli303 commented
link to #2114