Avoid throwing on invalid locale
CelestiaProject/Celestia pull request #2144
Opened 2024-03-05 19:44 UTC by ColinKinloch

This solves the issue mentioned here: https://github.com/CelestiaProject/Celestia/issues/2049#issuecomment-1963008789 where Celestia crashes if the specified locale does not exist.
I can trigger it by running `LC_ALL=C.ANSI_X3.4-1968 celestia-qt6`

This MR solves the issue as `std::locale()` does not throw.
However it changes the behavior to return either `std::locale::classic()` or the last value entered into `std::locale::global()`.

The original behavior can be restored by calling `std::locale::global(std::locale(""))`.
I'm not sure how to do this as the project uses `-fno-exceptions`.

2024-03-06 09:46 UTC, ColinKinloch commented
That's correct we could keep the same crashing behaviour by adding locale global.
Is there a way to ignore exceptions?

2024-03-06 11:52 UTC, ajtribick commented
I think we can check whether `setlocale` returns `nullptr` - we should probably do that at application start to avoid changing the global locale which results in thread safety issues. I'm not entirely sure that we should support such broken environments where the user's preferred locale does not exist, but maybe we can provide a cleaner error message on exit.

The usages of the `format` overloads that take a `locale` should be replaced by the `NumberFormatter` class - we expect these strings to be UTF-8 but on Windows it will return a string in the ANSI code page.

2024-03-06 17:29 UTC, ColinKinloch commented
Of course libc, always simplifies things.

>  I'm not entirely sure that we should support such broken environments

I don't disagree. On the other hand avoiding exceptions doesn't seem like too bad an idea.

Would I have to set the global locale in each front end, or is  there some appropriate common location?

2024-03-10 09:00 UTC, 375gnu requested changes
Could you also add a comment to the commit on `std::locale()` behavior?

2024-03-10 09:00 UTC, 375gnu commented on src/celutil/localeutil.cpp
> +    if (setlocale(LC_ALL, "")) {
```suggestion
    if (setlocale(LC_ALL, ""))
    {
```

2024-03-10 09:00 UTC, 375gnu commented on src/celutil/localeutil.cpp
> +    } else {
```suggestion
    }
    else
    {
```

2024-03-11 10:34 UTC, 375gnu approved these changes

2024-03-11 20:29 UTC, ajtribick approved these changes

2024-03-12 09:00 UTC, merged