Show Earth's mass and show all semi-axes for non spherical bodies
CelestiaProject/Celestia pull request #2193
Opened 2024-05-30 07:52 UTC by JiliTheSpaceboy

1. Make it so Earth's mass is shown, considering that Jupiter's mass is also shown even if it simply appears as 1.000 MJ

2. Objects that are neither spherical or use mesh now show mean radius along with all three semi-axes, using the following format:
Radius: mean (a × b × c)

3. kg masses can now uses scientific notation if sufficiently large. No more 20,000,000,000,000,000,000 kg, just 2E+19 kg.

2024-05-30 08:00 UTC, JiliTheSpaceboy commented
I don't know how to compile so this is untested and likely needs some fixing, so I decided to make a pull request.

2024-05-31 08:28 UTC, JiliTheSpaceboy commented
TODO:
- Make small masses (unit: kg) use scientific notation
- Move radius if elses into displayRadius function
- Clean up Radius display; for triaxial radii, make all values use the same unit and putting said unit only once at the end; possible dynamic sigfig?

2024-06-09 21:00 UTC, ajtribick requested changes

2024-06-09 21:00 UTC, ajtribick commented on src/celestia/hud.cpp
> +            overlay.print(_("Mass: {%.4g} kg\n"),
also needs to updates in formatnum.*

2024-06-13 17:30 UTC, JiliTheSpaceboy commented on src/celestia/hud.cpp
> +            overlay.print(_("Mass: {%.4g} lb\n"),
Should I just switch this back for now? Unless a proper developer is willing to work on this (maybe as part of your current plan to upgrade the Radius display?), I'm not sure I can handle this one.

2024-06-13 18:52 UTC, ajtribick commented on src/celestia/hud.cpp
> +            overlay.print(_("Mass: {%.4g} lb\n"),
Yep, I think the other changes in this to add the semiaxes and fix the missing mass are pretty useful, so let's keep those

2024-06-13 22:13 UTC, JiliTheSpaceboy commented on src/celestia/hud.cpp
> +            overlay.print(_("Mass: {%.4g} lb\n"),
I've reverted that part.

2024-06-15 06:16 UTC, ajtribick approved these changes

2024-06-15 09:07 UTC, 375gnu commented on src/celestia/hud.cpp
> +        double radiusMean = cbrt(semiAxes.prod());
```suggestion
        Eigen::Vector3f semiAxes = body.getSemiAxes();
        double radiusMean = cbrt(semiAxes.prod());
```

2024-06-15 09:08 UTC, 375gnu commented on src/celestia/hud.cpp
> +    Eigen::Vector3f semiAxes = body.getSemiAxes();
```suggestion
```

2024-06-15 09:21 UTC, merged