Add view port effect for post processing
CelestiaProject/Celestia pull request #846
Opened 2020-10-06 06:34 UTC by levinli303

When we need to apply a viewport effect, we first render to a texture, then render the texture with effect on screen. This will be needed for fisheye warping.

Configure in celestia.cfg:
1. Passthrough effect, just draw the same thing from the texture to the screen. `ViewportEffect "passthrough"`
2. Warp mesh effect, warping according to the warp mesh file provided. `ViewportEffect "warpmesh" WarpMeshFile "some warp mesh file name in the warp folder"`

2020-10-06 07:01 UTC, levinli303 commented
Need to be tested, so far it works ok on Mac and iOS.  Used [warp.zip](https://github.com/CelestiaProject/Celestia/files/5331887/warp.zip) for testing the warpmesh.

2020-10-06 17:26 UTC, 375gnu commented
i would like not to have GL calls in any celestia/* files, could you move them to celengine/ introducing new helper classes if necessary. another problem is oldfbo in FBO class, this violates encapsulation rules.

2020-10-07 01:52 UTC, levinli303 commented
@375gnu  maybe we can just move the glClear(Color) to inside ViewportEffect? The others are not direct GL calls, except for generating FBOs which I can't seem to find a trivial way to move to celengine since it is tied to view.

2020-10-07 07:36 UTC, 375gnu commented
> maybe we can just move the glClear(Color) to inside ViewportEffect?

yes, this sounds reasonable

2020-10-08 07:53 UTC, levinli303 commented
> > maybe we can just move the glClear(Color) to inside ViewportEffect?
> 
> yes, this sounds reasonable

this PR should be ready now.

2020-10-08 08:29 UTC, 375gnu commented
@levinli303 i'm still isn't happy with FBO unbinding. Generally we need to know if there is any FBO bound only in `renderGeometry_GLSL` . We can save currently bound FBO id before calling `renderGeometryShadow_GLSL` and restore it after. In this case `FramebufferObject` will remain the same.

2020-10-08 08:50 UTC, levinli303 commented
I think this is how it is done here. I added this here because OpenGLES on iOS's default FBO to render to is not 0.

2020-10-09 20:13 UTC, 375gnu requested changes
please add a description about warp algorithm used, at least a link to documentation

i'm still unhappy with FBO usage in CelestiaCore and FBO switching in unbind(), but at least for now we can live with this and will refactor this code later

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/mapmanager.cpp
> +extern WarpMeshManager* GetWarpMeshManager()
please remove `extern` and move `static WarpMeshManager* warpMeshManager = nullptr;` into the function body

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/mapmanager.cpp
> +    {
no need for braces here

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/mapmanager.cpp
> +    return "";
please use `return {}` here

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/mapmanager.cpp
> +    ifstream f(name.c_str());
please change to `name.string()`

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/mapmanager.h
> +public:
please add a space before `public` & `private`

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/mapmanager.h
> +extern WarpMeshManager* GetWarpMeshManager();
no need for `extern`

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/viewporteffect.cpp
> +VOViewportEffect::VOViewportEffect(GLenum bufferType, GLsizeiptr bufferSize, GLenum streamType) : vo(bufferType, bufferSize, streamType)
please move `vo(...)` to the next line

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/viewporteffect.cpp
> +PassthroughViewportEffect::PassthroughViewportEffect() : VOViewportEffect(GL_ARRAY_BUFFER, 0, GL_STATIC_DRAW)
please move `VOViewportEffect(...)` to  the next line

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/viewporteffect.cpp
> +WarpMeshViewportEffect::WarpMeshViewportEffect(WarpMesh *mesh) : VOViewportEffect(GL_ARRAY_BUFFER, 0, GL_STATIC_DRAW), mesh(mesh) {}
as above

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/mapmanager.h
> +#ifndef _MAPMANAGER_H_
please use `#pragma once`

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/viewporteffect.h
> +    virtual std::string getShaderName() = 0;
this method should be `const`

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/viewporteffect.cpp
> +bool ViewportEffect::distortXY(float &x, float &y) { return true; };
please make multiline

2020-10-09 20:13 UTC, 375gnu commented on src/celengine/viewporteffect.h
> +class VOViewportEffect : public ViewportEffect
do we really need yet another virtual subclass?

2020-10-10 12:16 UTC, 375gnu approved these changes
let's roll

2020-10-10 12:18 UTC, merged