Support fisheye projection
CelestiaProject/Celestia pull request #851
Opened 2020-10-10 12:32 UTC by levinli303

Basically adding the same things to every shader, is there a better approach?  Values that depend on FOVs also needs to be worked on.

2020-10-15 19:23 UTC, 375gnu commented
i think this should look as following:
1. fisheye function is in a separate file, e.g. `shaders/fisheye.h`
2. after `#version ...` we add `#define FISHEYE` if fish eye projection is required
3. then we add `#ifdef FISHEYE\n#include <fisheye.h>\n#endif`
4. in the main body `if (fisheye) { ... } else { ... }` is replaced with `#ifdef FISHEYE\nfisheye(inPos)\n#else\n...\n#endif`
5. in `shaderproperties.cpp` in `bool operator<(const ShaderProperties& p0, const ShaderProperties& p1)` add `if (p0.fisheye != p1.fisheye) return int(p0.fisheye) < int(p1.fisheye);`

2020-10-16 04:34 UTC, levinli303 commented
@375gnu  can we use include in GLSL?

2020-10-16 08:01 UTC, 375gnu commented
Forgot to say that glsl doesn't support `#include` so the usual way is to check if a file contains it and replace with actual content.

2020-11-16 06:26 UTC, levinli303 commented
Finished a dumb version where fisheye is set ShaderManager. for shaderproperties  we could have a property like that, but for shaders from files, I haven't found a viable way

2020-11-18 13:03 UTC, 375gnu requested changes

2020-11-18 13:03 UTC, 375gnu commented on src/celestia/celestiacore.cpp
> +static const float stdFOV = degToRad(60.0f);
shouldn't this be controlled by fish eye mode?

2020-11-18 13:03 UTC, 375gnu commented on src/celestia/celestiacore.cpp
> +                v->observer->setFOV((float) MaximumFOV);
MaximumFOV is already float

2020-11-18 13:03 UTC, 375gnu commented on src/celengine/shadermanager.cpp
> +uniform bool fisheye;
this uniform is not used anywhere

2020-11-18 13:03 UTC, 375gnu commented on src/celengine/shadermanager.cpp
> +BooleanShaderParameter
BooleanShaderParameter is not used anywhere

2020-11-18 14:53 UTC, levinli303 commented
should have fixed all the issues. also disabled the star glare rendering on fisheye for now

2020-11-20 14:17 UTC, 375gnu requested changes

2020-11-20 14:17 UTC, 375gnu commented on src/celengine/observer.cpp
> +    float r = sqrt(x * x + y * y);
you can replace with `hypot` here

2020-11-20 15:20 UTC, levinli303 commented on src/celengine/observer.cpp
> +    float r = sqrt(x * x + y * y);
fixed

2020-11-20 15:44 UTC, levinli303 commented
let's merge this

2020-11-20 15:51 UTC, 375gnu approved these changes
let's merge

2020-11-20 15:52 UTC, merged