Wording improvements to bg.po
CelestiaProject/Celestia pull request #899
Opened 2020-12-25 12:13 UTC by RacerBG

I already made this changes in Transifex. If no further changes are made to the strings in the 1.7.x branch - I believe this should be the final version of my Bulgarian translation.

Merry Christmas!

2020-12-26 00:34 UTC, levinli303 commented
Merry Christmas. I think there are some CI issues that need to be resolved before we can merge this.

2020-12-26 09:51 UTC, RacerBG commented
> 
> 
> Merry Christmas. I think there are some CI issues that need to be resolved before we can merge this.

I see but how I can do this? Unfortunately I'm not using git - I'm just using the GitHub infrastructure.

2020-12-26 09:53 UTC, levinli303 commented
@RacerBG you don't need to do anything. we need to merge this https://github.com/CelestiaProject/Celestia/pull/900 first

2020-12-26 10:22 UTC, RacerBG commented
> 
> 
> @RacerBG you don't need to do anything. we need to merge this #900 first

That's a big relief, thank you very much @levinli303 !

2020-12-29 06:30 UTC, 375gnu requested changes

2020-12-29 06:30 UTC, 375gnu commented on po/bg.po
> +#, fuzzy
this line should be removed

2020-12-30 07:17 UTC, 375gnu requested changes
please merge commits into a single one

2020-12-30 16:55 UTC, RacerBG commented
> 
> 
> please merge commits into a single one

@375gnu Any way to do that from the site interface, I don't have git?

2020-12-30 18:46 UTC, 375gnu commented
unfortunately without local `git` this is not possible

2020-12-30 19:38 UTC, RacerBG commented
> 
> 
> unfortunately without local `git` this is not possible

Looks like the only feasible solution then is to create this PR again (with everything included) and to close the current one.

2021-01-01 08:58 UTC, closed without merging

2021-01-01 09:02 UTC, RacerBG commented
Superseded by #903 .